feat: 'reset' can be in login forms too
duckduckgo/duckduckgo-autofill pull request #628
Opened 2024-08-06 08:55 UTC by dbajpeyi

**Reviewer:** 
**Asana:** 

## Description

## Steps to test

2024-08-06 09:31 UTC, GioSensation requested changes
I'm pretty sure this will trigger some regression for reset password forms, but it's hard to say how prominent the regression would be. Since this site is pretty prominent, let's go with this fix. Please add a test form in the `test-forms` suite so that if we ever go back and change this, we can be sure we don't regress here (or we can decide we're happy with that regression).

Send it back to me when you're done 🙂.

2024-08-07 04:31 UTC, dbajpeyi commented
I am fairly certain at least the major regressions (the netflix form e.g) should have caught this, I couldn't find why reset was used here, but that's the thing with regex. 

Meanwhile added some tests, and refactors.

2024-08-07 07:38 UTC, GioSensation requested changes
Sorry, I meant the test suite described in https://github.com/duckduckgo/duckduckgo-autofill/blob/main/docs/real-world-html-tests.md, not playwright.

2024-08-07 10:17 UTC, dbajpeyi commented on src/Form/matching-config/matching-config-source.js
> +                    match: 'new|re.?(enter|type)|repeat|update\\b'
This is the only relevant business logic change, other changes refactors. And there are tests of course!

2024-08-08 09:23 UTC, shakyShane approved these changes

2024-08-08 09:32 UTC, merged